name: financial_project_env 

channels:
  - conda-forge 
  - defaults

dependencies:
  - python>=3.10  
  - pip  
  - numpy>=1.21.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0  
  - scikit-learn>=1.0.0 
  - yfinance>=0.1.70  
  - jupyter 
  - catboost>=1.0.0

  - pip:
      - black
      - isort
      - ruff<0.0.280
      - nbqa
      - pre-commit