[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 88
known_third_party = ["numpy", "pandas", "matplotlib", "seaborn", "sklearn", "yfinance"]

[tool.ruff]
line-length = 88
preview = true

[tool.ruff.lint]
select = ["E", "F", "W"]
fixable = ["ALL"]
