data:
  raw_dir: data/raw
  target: y
  drop_cols:
  - id
  yn_binary_cols:
  - default
  - housing
  - loan
  use_duration: false
  val_size: 0.2
  random_state: 42
  subsample_rows: null
features:
  numeric:
  - age
  - balance
  - day
  - duration
  - campaign
  - pdays
  - previous
  categorical:
  - job
  - marital
  - education
  - default
  - housing
  - loan
  - contact
  - month
  - poutcome
  add_pdays_indicator: true
models:
  logreg:
    type: logreg
    params:
      C: 1.0
      max_iter: 1000
      class_weight: balanced
      n_jobs: -1
  rf:
    type: rf
    params:
      n_estimators: 300
      max_depth: null
      n_jobs: -1
      random_state: 42
      class_weight: balanced
  hgbt:
    type: hgbt
    params:
      max_depth: null
      learning_rate: 0.1
      max_leaf_nodes: 31
      random_state: 42
  catboost:
    type: catboost
    params:
      iterations: 500
      depth: 6
      learning_rate: 0.1
      loss_function: Logloss
      eval_metric: AUC
      random_seed: 42
      verbose: false
      allow_writing_files: false
thresholds:
  tune_on_valid: true
  default: 0.5
artifacts:
  dir: artifacts
