name: ci
on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest
          echo "PYTHONPATH=src" >> $GITHUB_ENV

      - name: Lint
        run: |
          . .venv/bin/activate
          ruff check .
          black --check .
          isort --check-only .

      - name: Tests
        run: |
          . .venv/bin/activate
          pytest -q
